#!/usr/bin/python
import sys

if len(sys.argv) < 2:
  print "Incorrect number of arguements."
  exit()

outfn = raw_input('Output file:')
with open(outfn,'w') as outf:
  outf.write('[\n')
  for jfn in sys.argv[1:-1]:
    outf.write(open(jfn,'r').read())
    outf.write(',\n')
  outf.write(open(sys.argv[-1],'r').read())
  outf.write('\n]')
